/* 
   File:   main
   Author: Renwei Miao  
   Created on September, 17, 2016, 4:46PM
   Purpose: Money generated by the company 
 */

//System Libraries
#include <iostream>   //Input/Output objects
#include <cstdlib>
using namespace std;  //Name-space used in the System Library

//User Libraries

//Global Constants

//Function prototypes

//Execution Begins Here!
int main(int argc, char** argv) {
    //Declaration of Variables
    double PercenTotal= 0.58;
    double SalesPer= 8.6;
    double MonGenrat;
    
    //Input values
    
    //Process values -> Map inputs to Outputs
    MonGenrat= SalesPer*PercenTotal;
    
    //Display Output
    cout<<"East Coast division will generate "<<MonGenrat;
    cout<<"million dollars this year"<<endl;
    //Exit Program
    return 0;
}